-- Run this once in Supabase Dashboard -> SQL Editor.
create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) <= 120),
  email text not null check (char_length(email) <= 255),
  subject text check (char_length(subject) <= 200),
  message text not null check (char_length(message) <= 10000),
  created_at timestamptz not null default now()
);

alter table public.contact_submissions enable row level security;

-- The backend inserts with the service-role key, so no public insert/select policy is needed.
create index if not exists contact_submissions_created_at_idx
  on public.contact_submissions (created_at desc);
